[package]
name = "s3db"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gob = "0.1.0"
serde = { version = "1.0.130", features = ["derive"] }

